//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawnshop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyPayments
    {
        public int IDMonthlyPayment { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Sum { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<System.DateTime> FactPayment { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual StatusesOfPayments StatusesOfPayments { get; set; }
    }
}
